global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Scrape the Spring Boot Actuator Prometheus endpoint
  - job_name: "flowbridge-finance-tracker"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8081"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
